### ISSUE TITLE
官网文档配置文件不详补充。v=1.5.1

### ISSUE THREAD

**Issue by AbboWw** [seata/seata.github.io#476]
部署包：seataio/seata-server:1.5.1
1、无法使用老版本registry配置文件启动。会默认读取${SEATA_HOME}/resourse/application.yml配置
2、使用application.example.yml部署seata。需要添加以下配置，不然启动报错。

```yaml
console:
  user:
    username: xxx
    password: xxx
```

```yaml
seata:
  security:
    secretKey: xxx
    tokenValidityInMilliseconds: 10000
```

docker-compose和K8s栏目无更新，docker部署栏目更新不太好看见，且缺少配置参数，需启动抛出异常才能看到缺少配置文件
